[package]
name = "VersionManager"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
tokio = {version = "1.42.0", features = ["full"]}
scraper = "0.22.0"
clap = { version = "4.5.23", features=["derive"]}
serde_json="1.0.133"